name: Surge
version: '0.1'
main: dev.eychro.surge.Surge
api-version: '1.21'
authors: [eychro]
description: HubCore
commands:
  fly:
    description: 'Allow you to fly'
    usage: /<command>
    aliases: [ Flight ]