name: Surge
version: '${project.version}'
main: dev.eychro.surge.Surge
author: 'Eychro'
commands:
  vanish:
    aliases:
      - vanish
  reload:
    aliases:
      - reload
  fly:
    aliases:
      - fly